name: Run binary in different java versions

on:
  workflow_dispatch:

env:
  LATEST_TAG: gradle/ge-instance-monitor:latest

jobs:
  build:
    strategy:
      matrix:
        java: [8,11,17]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  ${{ matrix.java }}

      - name: Prepare a build with nowinandroid
        run: |
          curl -L https://github.com/cdsap/ProjectReport/releases/download/v.0.3.0/projectreport --output projectreport
          chmod 0757 projectreport
          ./projectreport --max-builds=10000 --api-key=${{ secrets.GE_API_KEY }} --url=${{ secrets.GE_URL }}
